[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node openclaw.mjs config set gateway.bind lan && node openclaw.mjs config set gateway.port 8082 && node openclaw.mjs config set gateway.controlUi.dangerouslyAllowHostHeaderOriginFallback true && node openclaw.mjs config set gateway.httpServer.port 8082 && node openclaw.mjs config set gateway.httpServer.bind lan && sleep 2 && node openclaw.mjs gateway --allow-unconfigured"
